### PR TITLE
Fix "invalid lib version" crash

### LINKED ISSUE #7917: IDE won't start after installing a library with an invalid version
Using Arduino IDE 1.8.6/Arduino IDE 1.8.6 Hourly Build 2018-08-23 11:33/Arduino 1.9.0-beta build 80 on Windows 10 64 bit

When a library is installed with an invalid value in its library.properties `version` field the Arduino IDE will not start.

1. Download [xbee_serial_array-master.zip](https://github.com/arduino/Arduino/files/2316802/xbee_serial_array-master.zip)
1. Sketch > Include Library > Add .ZIP Library... > select the downloaded file > Open
1. File > Quit
1. Attempt to run the Arduino IDE - It does not start.

arduino_debug.exe output:
```
C:\ArduinoIDE\arduino-1.8.6>arduino_debug.exe
Loading configuration...
Initializing packages...
Preparing boards...
Invalid version found: 0.9a
java.lang.NullPointerException
        at processing.app.packages.UserLibrary.create(UserLibrary.java:156)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanLibrary(LibrariesIndexer.java:213)
        at cc.arduino.contributions.libraries.LibrariesIndexer.scanInstalledLibraries(LibrariesIndexer.java:190)
        at cc.arduino.contributions.libraries.LibrariesIndexer.rescanLibraries(LibrariesIndexer.java:150)
        at cc.arduino.contributions.libraries.LibrariesIndexer.setLibrariesFolders(LibrariesIndexer.java:109)
        at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:677)
        at processing.app.Base.onBoardOrPortChange(Base.java:1313)
        at processing.app.Base$11.actionPerformed(Base.java:1514)
        at processing.app.Base.rebuildBoardsMenu(Base.java:1490)
        at processing.app.Base.<init>(Base.java:267)
        at processing.app.Base.main(Base.java:145)
```
The problem does not occur with Arduino IDE 1.8.5.

### PR DESCRIPTION
**Pull request by cmaglie**
Fix #7917 

The actual fix is https://github.com/arduino/Arduino/commit/6e030b857343dba0525d0cbf2c2573858c730edb, BTW I've added some more commits to clean up things out.

### CODE REVIEW

File: arduino-core/src/processing/app/packages/UserLibrary.java [hunk 1]
```diff
@@ -148,12 +152,16 @@ public static UserLibrary create(UserLibraryFolder libFolderDesc) throws IOExcep
...
+    if (!version.isPresent()) {
+      System.out.println(
+          format(tr("Invalid version '{0}' for library in: {1}"), declaredVersion, libFolder.getAbsolutePath()));
+    }
 
     UserLibrary res = new UserLibrary();
     res.installedFolder = libFolder;
     res.name = properties.get("name").trim();
-    res.version = version.toString();
+    res.version = version.isPresent() ? version.get().toString() : declaredVersion;
```
Comment (PaulStoffregen) [inline arduino-core/src/processing/app/packages/UserLibrary.java]: Could using "declaredVersion" have unintended consequences?  As I understand this, it would allow libraries to put any arbitrary string into Arduino's data structures.  Is everything else in the Arduino code able to handle any arbitrary text, when it's all been designed around the until-now strictly enforced major.minor.patch format?

Comment (cmaglie) [reply arduino-core/src/processing/app/packages/UserLibrary.java]: The `version` field for user libraries has always been a `String` and the format has never been forced to be semver compliant.

To compare version "strings" we use the [`VersionComparator`](https://github.com/arduino/Arduino/blob/fb5ed00547ae394784bee2bd9f617fdf4f54ebf5/arduino-core/src/cc/arduino/contributions/VersionComparator.java) class that compares two different version "strings", say A and B, using the following alogrithm:

1. parse A and B as semver
2. if both A and B are valid semver, compare them using semver rules
3. if A is valid semver but not B, then A is the greatest
4. if B is valid semver but not A, then B is the greatest
5. if both A and B are not valid semver, consider them equals

This logic allows libraires that are not semver compliant to soft transition to semver (since a valid semver version is always greater).

Comment (PaulStoffregen) [reply arduino-core/src/processing/app/packages/UserLibrary.java]: Ok, sounds like you've thought this through quite carefully.  I was thinking simpler less-is-more in #7922, after having a user reports 1.8.6 unable to start up.

**Comment by per1234** [comment]
Fixes https://github.com/arduino/Arduino/issues/3215
:+1:
